# Generated by Django 5.0.2 on 2024-02-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lastName',
        ),
    ]
